
export const PRODUCTS = {
  GET_ALL_PRODUCTS_REQUEST: 'GET_ALL_PRODUCTS_REQUEST',
  GET_ALL_PRODUCTS_ERROR: 'GET_ALL_PRODUCTS_ERROR',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  
  CREATE_PRODUCT_REQUEST: 'CREATE_PRODUCT_REQUEST',
  CREATE_PRODUCT_ERROR: 'CREATE_PRODUCT_ERROR',
  CREATE_PRODUCT: 'CREATE_PRODUCT',

  GET_SINGLE_PRODUCT_REQUEST: 'GET_SINGLE_PRODUCT_REQUEST',
  GET_SINGLE_PRODUCT_ERROR: 'GET_SINGLE_PRODUCT_ERROR',
  GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',

  DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
  DELETE_PRODUCT_ERROR: 'DELETE_PRODUCT_ERROR',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
};

export const CATEGORY = {
  GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
  GET_CATEGORIES_ERROR: 'GET_CATEGORIES_ERROR',
  GET_CATEGORIES: 'GET_CATEGORIES',

  GET_SINGLE_CATEGORY_REQUEST: 'GET_SINGLE_CATEGORY_REQUEST',
  GET_SINGLE_CATEGORY_ERROR: 'GET_SINGLE_CATEGORY_ERROR',
  GET_SINGLE_CATEGORY: 'GET_SINGLE_CATEGORY',
};
